name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          
      - name: Install Dependencies
        run: npm install
          
      - name: Build
        run: npm run build
          
      - name: Debug build directory
        run: |
          echo "Build directory contents:"
          ls -la build
          
      - name: 📂 Deploy to DreamHost
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: pdx1-shared-a1-25.dreamhost.com
          username: dh_2bzpfx
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftp
          local-dir: ./build/
          server-dir: /home/dh_2bzpfx/summercamping2025.com/
          dangerous-clean-slate: true 