name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          
      - name: Install Dependencies
        run: npm install
          
      - name: Build
        run: npm run build
          
      - name: Debug build directory
        run: |
          echo "Build directory contents:"
          ls -la build
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          name: id_ed25519
          
      - name: Debug SSH setup
        run: |
          echo "SSH directory contents:"
          ls -la ~/.ssh/
          echo "SSH key permissions:"
          stat ~/.ssh/id_ed25519
          echo "Public key content:"
          ssh-keygen -y -f ~/.ssh/id_ed25519
          echo "Testing SFTP connection:"
          sftp -v dh_2bzpfx@pdx1-shared-a1-25.dreamhost.com <<< "quit"
          
      - name: Create SFTP batch file
        run: |
          echo "cd /home/dh_2bzpfx/summercamping2025.com/" > sftp_batch
          echo "rm -rf *" >> sftp_batch
          cd build && find . -type f -print0 | while IFS= read -r -d '' file; do
            echo "put \"$file\" \"${file#./}\"" >> ../sftp_batch
          done
          
      - name: Deploy to DreamHost via SFTP
        run: |
          sftp -b sftp_batch dh_2bzpfx@pdx1-shared-a1-25.dreamhost.com 