name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
          
      - name: Build
        env:
          PUBLIC_URL: https://summercamping2025.com
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build
          
      - name: Debug build directory
        run: |
          echo "Build directory contents:"
          ls -la build
          
      - name: Deploy to DreamHost
        uses: pressidium/lftp-mirror-action@v1
        env:
          LFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        with:
          host: pdx1-shared-a1-25.dreamhost.com
          user: dh_2bzpfx
          pass: ${{ env.LFTP_PASSWORD }}
          remoteDir: /home/dh_2bzpfx/summercamping2025.com
          localDir: ./build
          reverse: true
          ignoreFile: .gitignore
          options: --verbose --delete 