name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
          
      - name: Build
        env:
          PUBLIC_URL: https://summercamping2025.com
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build

      - name: Check DNS
        run: |
          echo "Checking DNS records..."
          nslookup summercamping2025.com
          echo "Checking web server..."
          curl -I http://summercamping2025.com || true
          curl -I https://summercamping2025.com || true
          
      - name: Deploy to DreamHost via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: pdx1-shared-a1-25.dreamhost.com
          user: dh_2bzpfx
          pass: ${{ secrets.FTP_PASSWORD }}
          localDir: ./build
          remoteDir: .
          options: --verbose --reverse --delete-first

      - name: Set permissions and verify files
        uses: appleboy/ssh-action@master
        with:
          host: pdx1-shared-a1-25.dreamhost.com
          username: dh_2bzpfx
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            echo "Home directory contents before:"
            pwd
            ls -la
            echo "Setting permissions..."
            find . -maxdepth 1 -type d -exec chmod 755 {} \;
            find . -maxdepth 1 -type f -exec chmod 644 {} \;
            echo "Directory contents after:"
            ls -la
            echo "Checking index.html:"
            cat index.html | head -n 5
            echo "Current directory:"
            pwd
            echo "User and groups:"
            id
            groups 