name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
          
      - name: Build
        env:
          PUBLIC_URL: https://summercamping2025.com
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build
          
      - name: Deploy to DreamHost via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: pdx1-shared-a1-25.dreamhost.com
          user: dh_2bzpfx
          pass: ${{ secrets.FTP_PASSWORD }}
          localDir: ./build
          remoteDir: /home/dh_2bzpfx/summercamping2025.com
          options: --verbose --reverse --delete-first

      - name: Set permissions
        uses: appleboy/ssh-action@master
        with:
          host: pdx1-shared-a1-25.dreamhost.com
          username: dh_2bzpfx
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd /home/dh_2bzpfx/summercamping2025.com
            find . -type d -exec chmod 755 {} \;
            find . -type f -exec chmod 644 {} \;
            ls -la 